name: "Mr Truth Development"
description: "Mr Truth - Tentando descomplicar o desenvolvimento de software"

url: "[YOUR DOMAIN]"

paginate: 5

permalink: pretty

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
    -
        scope:
            path: ""
        values:
            timezone:  America/Sao_Paulo
            layout: "default"
    
    
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']